### PR TITLE
Fix: LLVM assertion failure with empty routes (take 2)

### LINKED ISSUE #1: Can't build on OS X 10.11
`make run` fails with the error

```
Assertion failed: ((i >= FTy->getNumParams() || FTy->getParamType(i) == Args[i]->getType()) && "Calling a function with a bad signature!"), function init, file /tmp/llvm20151214-69554-hagc7s/llvm-3.6.2.src/lib/IR/Instructions.cpp, line 281.
```

### PR DESCRIPTION
**Pull request by ysbaddaden**
fixes #1 (hopefully) until new compiler is released

### CODE REVIEW

**Comment by ysbaddaden** [comment]
Oh, this is interesting: the culprit is (now?) `test/dispatcher_test.cr` which does define routes. All other tests are compiling fine (even the empty route one). That's weird.

**Comment by sdogruyol** [comment]
The CI checks are OK did this just pass?

**Comment by ysbaddaden** [comment]
No, this was a test that highlighted that the bug is in `test/dispatcher_test.cr`, so no longer in the empty route set, but in one with routes. The way I wrote the Makefile, it wrongly passed.

I'm trying to reproduce on a Linux box, but so far I've been unlucky. That looks like it affects only the OS X toolchain :-/

**Comment by ysbaddaden** [comment]
I can't reproduce the bug on Linux :dizzy_face: 

I installed a fresh Ubuntu Trusty (in a container); installed the latest LLVM 3.6 from http://llvm.org/apt; made clang the default compiler (instead of gcc); compiled Crystal 0.10.0 from sources using clang (then recompiled it again using the built compiler, just to be sure). I eventually ran the Frost test suite... and it passed.

**Comment by ysbaddaden** [comment]
CI failure is unrelated (sadly). Or more likely: same bug but different cause...

**Pull request merged**
